version: '3.7'
services:
  hapi-template:
    build:
      context: .
      target: development
    image: hapi-template
    container_name: hapi-template
    command: npm run start:watch
    ports:
      - "3000:3000"
    volumes:
      - ./app/:/home/node/app/
      - ./package.json:/home/node/package.json
