version: '3'
services:
  hapi-template:
    build: .
    image: hapi-template
    container_name: hapi-template
    command: npm run start:watch
    ports:
      - "3000:3000"
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app

volumes:
  node_modules:
